const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

try {
  // 1. Run frontend build
  console.log('--- Step 1: Building Frontend ---');
  execSync('npm --prefix frontend install', { stdio: 'inherit' });
  execSync('npm --prefix frontend run build', { stdio: 'inherit' });

  // 2. Copy frontend/.vercel to .vercel at the root
  console.log('--- Step 2: Copying Frontend Build Output to Root ---');
  if (fs.existsSync(path.join('frontend', '.vercel'))) {
    if (fs.existsSync('.vercel')) {
      fs.rmSync('.vercel', { recursive: true, force: true });
    }
    fs.cpSync(path.join('frontend', '.vercel'), '.vercel', { recursive: true });
  } else {
    throw new Error('frontend/.vercel folder was not generated by the build process.');
  }

  // 3. Create the backend function directory under .vercel/output/functions
  const apiFuncDir = path.join('.vercel', 'output', 'functions', 'api', 'index.func');
  console.log(`--- Step 3: Creating Serverless API Function Directory: ${apiFuncDir} ---`);
  fs.mkdirSync(apiFuncDir, { recursive: true });

  // 4. Create the .vc-config.json file for Python serverless function
  console.log('--- Step 4: Writing Serverless Function Configuration (.vc-config.json) ---');
  const vcConfig = {
    runtime: 'python3.12',
    handler: 'index.app',
    launcherType: 'Nodejs',
    shouldAddHelpers: true
  };
  fs.writeFileSync(
    path.join(apiFuncDir, '.vc-config.json'),
    JSON.stringify(vcConfig, null, 2)
  );

  // 5. Copy the backend files to the api/index.func folder
  console.log('--- Step 5: Packaging Python Backend Source & Requirements ---');
  
  // Copy index.py and adjust path insertion to target the local directory
  let indexContent = fs.readFileSync(path.join('api', 'index.py'), 'utf8');
  indexContent = indexContent.replace(
    /os\.path\.join\(os\.path\.dirname\(__file__\),\s*"\.\.",\s*"backend"\)/g,
    'os.path.dirname(__file__)'
  );
  fs.writeFileSync(path.join(apiFuncDir, 'index.py'), indexContent);

  // Copy requirements.txt
  fs.copyFileSync(
    path.join('api', 'requirements.txt'),
    path.join(apiFuncDir, 'requirements.txt')
  );

  // Copy app folder recursively
  fs.cpSync(path.join('backend', 'app'), path.join(apiFuncDir, 'app'), { recursive: true });

  // Copy seed_db.py and migrate.py
  fs.copyFileSync(
    path.join('backend', 'seed_db.py'),
    path.join(apiFuncDir, 'seed_db.py')
  );
  fs.copyFileSync(
    path.join('backend', 'migrate.py'),
    path.join(apiFuncDir, 'migrate.py')
  );

  // 6. Update .vercel/output/config.json to include the rewrite for /api/(.*) -> /api/index
  console.log('--- Step 6: Injecting API Rewrite Rule into Deployment Config ---');
  const configPath = path.join('.vercel', 'output', 'config.json');
  if (fs.existsSync(configPath)) {
    const vercelConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    
    if (!vercelConfig.routes) {
      vercelConfig.routes = [];
    }
    
    // Check if API route already exists, if not insert it before the catch-all
    const apiRouteExists = vercelConfig.routes.some(r => r.src && r.src.includes('/api/'));
    if (!apiRouteExists) {
      const apiRoute = {
        src: '/api/(.*)',
        dest: '/api/index'
      };
      
      // Place the rewrite rule before the catch-all /(.*) -> /__server
      const catchAllIndex = vercelConfig.routes.findIndex(r => r.src === '/(.*)');
      if (catchAllIndex !== -1) {
        vercelConfig.routes.splice(catchAllIndex, 0, apiRoute);
      } else {
        vercelConfig.routes.push(apiRoute);
      }
      console.log('✅ API rewrite rule successfully injected.');
    } else {
      console.log('ℹ️ API rewrite rule already exists in config.json.');
    }
    
    fs.writeFileSync(configPath, JSON.stringify(vercelConfig, null, 2));
  } else {
    console.warn('⚠️ config.json was not found in .vercel/output. Routing might fail.');
  }

  console.log('🎉 Unified frontend and backend build completed successfully!');
} catch (error) {
  console.error('❌ Build script failed:', error);
  process.exit(1);
}
