/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as PaymentCancelledRouteImport } from './routes/payment-cancelled'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomainsIndexRouteImport } from './routes/domains.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as DomainsSlugRouteImport } from './routes/domains.$slug'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDomainsRouteImport } from './routes/admin.domains'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelledRoute = PaymentCancelledRouteImport.update({
  id: '/payment-cancelled',
  path: '/payment-cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsSlugRoute = DomainsSlugRouteImport.update({
  id: '/domains/$slug',
  path: '/domains/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/admin/register',
  path: '/admin/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDomainsRoute = AdminDomainsRouteImport.update({
  id: '/admin/domains',
  path: '/admin/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/payment-cancelled': typeof PaymentCancelledRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/domains/': typeof DomainsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/payment-cancelled': typeof PaymentCancelledRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminIndexRoute
  '/domains': typeof DomainsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/payment-cancelled': typeof PaymentCancelledRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/domains': typeof AdminDomainsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/domains/$slug': typeof DomainsSlugRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/domains/': typeof DomainsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/payment-cancelled'
    | '/payment-failed'
    | '/payment-success'
    | '/unauthorized'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/domains'
    | '/admin/login'
    | '/admin/register'
    | '/admin/settings'
    | '/admin/transactions'
    | '/domains/$slug'
    | '/projects/$id'
    | '/admin/'
    | '/domains/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/payment-cancelled'
    | '/payment-failed'
    | '/payment-success'
    | '/unauthorized'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/domains'
    | '/admin/login'
    | '/admin/register'
    | '/admin/settings'
    | '/admin/transactions'
    | '/domains/$slug'
    | '/projects/$id'
    | '/admin'
    | '/domains'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/payment-cancelled'
    | '/payment-failed'
    | '/payment-success'
    | '/unauthorized'
    | '/admin/contacts'
    | '/admin/dashboard'
    | '/admin/domains'
    | '/admin/login'
    | '/admin/register'
    | '/admin/settings'
    | '/admin/transactions'
    | '/domains/$slug'
    | '/projects/$id'
    | '/admin/'
    | '/domains/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PaymentCancelledRoute: typeof PaymentCancelledRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDomainsRoute: typeof AdminDomainsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  DomainsSlugRoute: typeof DomainsSlugRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-cancelled': {
      id: '/payment-cancelled'
      path: '/payment-cancelled'
      fullPath: '/payment-cancelled'
      preLoaderRoute: typeof PaymentCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$slug': {
      id: '/domains/$slug'
      path: '/domains/$slug'
      fullPath: '/domains/$slug'
      preLoaderRoute: typeof DomainsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/admin/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/domains': {
      id: '/admin/domains'
      path: '/admin/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AdminDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PaymentCancelledRoute: PaymentCancelledRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDomainsRoute: AdminDomainsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  DomainsSlugRoute: DomainsSlugRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DomainsIndexRoute: DomainsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
